name: 'Terraform GitHub Actions'
on:
  workflow_dispatch:
    # Inputs the workflow expects.
    inputs:
      tf_confirm:
        description: 'Confirm Terraform Execution'     
        required: true
        type: boolean
    paths:
      - '.github/workflows/terraform.yml'
defaults:
  run:
    working-directory: terraform
  
jobs:
  deploy:
    name: 'Terraform plan/deploy'
    runs-on: ubuntu-latest
    if:  ${{ inputs.tf_confirm }}  
    steps:
      - 
        name: check out the repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.2' 

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Workspace
        id: workspace
        run: terraform workspace new ${{ github.head_ref || github.ref_name }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
      
      # - name: Terraform Apply
      #   id: apply
      #   run: terraform apply -auto-approve
      
      # - name: Terraform Destroy
      #   id: destroy
      #   run: terraform apply -destroy -auto-approve


